name: 'SnapVibe Deploy Action'
author: 'SnapVibe'
branding:
  icon: 'terminal'
  color: 'white'
description: 'SnapVibe Server Manifest File Update Action'

inputs:
  language:
    description: 'SnapVibe Service Build Language (spring / go)'
    required: true
  service_name:
    description: 'SnapVibe Service Name'
    required: true
  service_port:
    description: 'SnapVibe Service Port'
    required: true
  service_prefix:
    description: 'SnapVibe Service prefix'
    required: false
    

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Call Spring Service Build action
      id: call-spring-build
      if: inputs.language == 'spring'
      uses: Masasak/v1-deploy-gh-action/actions/spring-build
    
    - name: Call Go Service Build action
      id: call-go-build
      if: inputs.language == 'go'
      uses: Masasak/v1-deploy-gh-action/actions/go-build
